os: freebsd
addons:
pkg:
- llvm

jobs:
  include:
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - getconf LONG_BIT
        - dmesg | grep CPU
        - dmesg | grep memory
        - echo "FreeBSD sysinfo Travis repo by Montana Mendy"
