language: c
compiler:
  - clang
  - gcc
install: chmod u+x ./autogen.sh

jobs:
  include:
    - os: freebsd
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - getconf LONG_BIT
        - dmesg | grep CPU
        - dmesg | grep memory
        - cd src
        - clang armstrong.c
