language: c
install: skip
os: freebsd

jobs:
  include:
    - os: freebsd
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - getconf LONG_BIT
        - dmesg | grep CPU
        - dmesg | grep memory
        - sysctl -a | less
        - cd src
        - clang armstrong.c
